<?php

namespace AppBundle\Repository;

/**
 * AccesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesoRepository extends \Doctrine\ORM\EntityRepository
{
}
