<?php

namespace AppBundle\Repository;

/**
 * CheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckRepository extends \Doctrine\ORM\EntityRepository
{
}
