<?php

namespace AppBundle\Repository;

/**
 * TieneAccesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TieneAccesoRepository extends \Doctrine\ORM\EntityRepository
{
}
